global-styling:
  css:
    base:
      css/base/base.css: {}
      css/base/buttons.css: {}
      css/base/typography.css: {}
      css/base/utility.css: {}
      css/base/misc.css: {}
    component:
      css/components/form.css: {}
      css/components/node.css: {}
      css/components/nodenav.css: {}
      css/components/images.css: {}
views:
  css:
    theme:
      css/components/views-exposed-form.css: {}
      css/components/block.css: {}

  dependencies:
    - core/components.drupal_tv--card
view-search:
  css:
    layout:
      css/layout/views-search.css: {}
search-api-autocomplete:
  css:
    component:
      css/components/search-api-autocomplete.css: {}
event-full:
  css:
    component:
      css/components/event-full.css: {}
case-study-full:
  css:
    component:
      css/components/case-study-full.css: {}
project-full:
  css:
    component:
      css/components/project-full.css: {}
person-full:
  css:
    component:
      css/components/person-full.css: {}
